"""
Base Template Module

Abstract base class for all output templates.
"""
from abc import ABC, abstractmethod
from typing import Dict, Any
from datetime import datetime

import sys
sys.path.insert(0, str(__file__).rsplit('/', 2)[0])

from services.rag_context_builder import RAGContext


class BaseTemplate(ABC):
    """
    Abstract base for output templates.

    All templates receive RAGContext and options,
    and produce formatted markdown output.
    """

    @property
    @abstractmethod
    def template_name(self) -> str:
        """Template identifier."""
        pass

    @abstractmethod
    def render(self, context: RAGContext, options: Dict[str, Any]) -> str:
        """
        Render the template with given context.

        Args:
            context: RAGContext from RAGContextBuilder
            options: Command-specific options

        Returns:
            Formatted markdown string
        """
        pass

    def _build_header(self, title: str, context: RAGContext) -> str:
        """Build standard header section."""
        story = context.story
        return "\n".join([
            f"# {title}: {story.get('key', 'UNKNOWN')}",
            f"**{story.get('title', story.get('summary', 'Untitled'))}**",
            "",
            f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
            "",
            "---",
            "",
        ])

    def _build_story_section(self, context: RAGContext) -> str:
        """Build story details section."""
        story = context.story
        lines = [
            "## Story Details",
            "",
            f"- **Key:** {story.get('key', 'N/A')}",
            f"- **Status:** {story.get('status', 'N/A')}",
            f"- **Priority:** {story.get('priority', 'N/A')}",
            f"- **Type:** {story.get('issue_type', 'N/A')}",
            "",
            "### Description",
            "",
            story.get('description', 'No description') or 'No description',
            "",
        ]

        ac = story.get('acceptance_criteria')
        if ac:
            lines.extend([
                "### Acceptance Criteria",
                "",
                ac if isinstance(ac, str) else "\n".join(ac),
                "",
            ])

        return "\n".join(lines)

    def _build_validation_summary(self, context: RAGContext) -> str:
        """Build validation results summary."""
        lines = ["## Validation Summary", ""]

        for name, result in context.validation_results.items():
            status = "PASS" if result.get("passed", True) else "FAIL"
            score = result.get("score", 1.0)
            lines.append(f"- **{name}:** {status} ({score:.0%})")

            findings = result.get("findings", [])
            for finding in findings[:3]:
                severity = finding.get("severity", "INFO")
                message = finding.get("message", "")
                lines.append(f"  - [{severity}] {message}")

        lines.append("")
        return "\n".join(lines)

    def _build_footer(self) -> str:
        """Build standard footer with anti-hallucination disclaimer."""
        return "\n".join([
            "---",
            "",
            "**IMPORTANT:** This analysis is based ONLY on:",
            "- Retrieved knowledge chunks from local knowledge base",
            "- Validator findings (state, financial, rule, cross-dep)",
            "- Story pre-analysis results",
            "",
            "If context is insufficient, sections indicate \"Insufficient Context\".",
            "",
            "*Generated by QA RAG System*",
            f"*Timestamp: {datetime.now().isoformat()}*",
        ])
